---
- name: Install AWX
  shell: ansible-playbook -i /root/awx/installer/inventory /root/awx/installer/install.yml
  notify: reboot awx server
#
- debug:
    msg: "After reboot access AWX: http://{{ ansible_facts['default_ipv4']['address'] }}"
...
