---
- name: Install Containerd.io
  yum:
    name: "{{ awx_docker_containerd }}"
    state: present
#
- name: Install Docker
  dnf:
    name: "{{ awx_docker }}"
    state: latest
#
- name: Start and enable docker service
  service:
    name: "{{ awx_docker_service }}"
    state: started
    enabled: true
...
